# Generated by Django 4.0.6 on 2022-09-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupons',
        ),
    ]
