# Generated by Django 4.0.6 on 2022-08-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
